server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /general/platform/admin
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/eob-platform-auth?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
      username: root
      password: 123456
      filters: stat,wall,slf4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

knife4j-propertys:
  title: General Platform Admin API
  description: 通用平台管理系统服务端接口
  termsOfServiceUrl: www.xiangliheart.com/general/platform/admin
  version: 1.0.0-SNAPSHOT
  basePackage: com.xiangliheart.general.platform
  groupName: 1.0.0-SNAPSHOT
  name: xiangliheart(湘澧寸心)
  url: www.xiangliheart.com
  email: xiangliheart@hotmail.com

