server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eob?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
swagger-plus-property:
  title: EOB Server Auth API
  description: EOB Server Auth API
  termsOfServiceUrl: www.baidu.com
  version: 1.0.0-SNAPSHOT
  basePackage: com.xiangliheart.eob.server.auth
  groupName: 1.0.0-SNAPSHOT
  name: xiangliheart(湘澧寸心)
  url: www.xiangliheart.com
  email: xiangliheart@163.com

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql